#!/bin/sh

# This file has been modified from the original.

# This script will only manage 32bit compatability drivers from nvidia.
# Superfluous functions and statements have been removed and text has been
# updated.

# Original copyright is as follows
# ***************************************************************************
# *   Copyright (C) 2007-2009 by Heinz Wiesinger                            *
# *   pprkut@liwjatan.at                                                    *
# *   http://www.liwjatan.at                                                *
# *                                                                         *
# *   This program is free software; you can redistribute it and/or modify  *
# *   it under the terms of the GNU General Public License as published by  *
# *   the Free Software Foundation; either version 3 of the License, or     *
# *   (at your option) any later version.                                   *
# *                                                                         *
# *   This program is distributed in the hope that it will be useful,       *
# *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
# *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
# *   GNU General Public License for more details.                          *
# *                                                                         *
# *   You should have received a copy of the GNU General Public License     *
# *   along with this program; if not, write to the                         *
# *   Free Software Foundation, Inc.,                                       *
# *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
# ***************************************************************************/
# nvidia-switch utility 0.8.0
#
# A tool to switch between 32bit nvidia-binary-driver and 32bit xorg-driver
# if both are installed in parallel.

set -e

ROOT="/"
CWD=$(pwd)
LIBSUFFIX="LIBDIRSUFFIX" # This will be replaced in the build script
LIB="${ROOT}usr/lib${LIBSUFFIX}"
NV_VERSION='PKGVERSION' # This will be replaced in the build script
GL_VERSION="1.2"

remove_link(){
if [ -L "$1" ]; then
  rm -f "$1"
fi
}

remove_existing(){
if [ -e "$1" ]; then
  rm -f $1
fi
}

move_existing(){
if [ -e "$1" ]; then
  mv $1 $2
fi
}

setup_link(){
  if [ "$1" = "mv" ]; then
    mv "$2" "$3"
  else
    rm -f $2
  fi
  ln -s "$3" "$2"
}

# incs() function not needed for compat32
# libs() function not needed for compat32

libs_basic(){
for i in libGL.so libGLcore.so; do
  #if this link exists, remove it, if it's a file, move it to *.nvidia
  if [ -L "$LIB/$i.$NV_VERSION" ]; then
    rm -f "$LIB/$i.$NV_VERSION"
  elif [ -e "$LIB/$i.$NV_VERSION" ]; then
    mv "$LIB/$i.$NV_VERSION" "$LIB/$i.$NV_VERSION-nvidia"
  fi
  remove_link "$LIB/$i.1"
done
}

libgl_nvidia(){
#if libGL.so.$GL_VERSION does exist, move it to libGL.so.$GL_VERSION-xorg, as it conflicts if nvidia's libGL.so
# then remove the libGL.so.1 symlink and create a new one pointing to nvidia's libGL.so
if [ -e "$LIB/libGL.so.$GL_VERSION" ]; then
  cd "$LIB"
  mv libGL.so.$GL_VERSION libGL.so.$GL_VERSION-xorg
  setup_link "" "libGL.so.1" "libGL.so.$NV_VERSION"
  cd "$CWD"
fi
}

libgl_xorg(){
#if libGL.so.$GL_VERSION does not exist and libGL.so.$GL_VERSION-xorg does, move it to libGL.so.$GL_VERSION
# then remove the libGL.so.1 symlink and create a new one pointing to nvidia's libGL.so
if [ -e "$LIB/libGL.so.$GL_VERSION" ]; then
  remove_existing "$LIB/libGL.so.$GL_VERSION-xorg"
else
  if [ -e "$LIB/libGL.so.$GL_VERSION-xorg" ]; then
    cd "$LIB"
    mv libGL.so.$GL_VERSION-xorg libGL.so.$GL_VERSION
    ln -s libGL.so.$GL_VERSION libGL.so.1
    cd "$CWD"
  fi
fi
}


libglcore_nvidia(){
#If libGLcore.so.$NV_VERSION-nvidia does exists, then remove the -nvidia and make it usable that way
if [ -e "$LIB/libGLcore.so.$NV_VERSION-nvidia" ]; then
  cd "$LIB"
  rm -f libGLcore.so.$NV_VERSION libGLcore.so.1
  ln -s libGLcore.so.$NV_VERSION-nvidia libGLcore.so.$NV_VERSION
  ln -s libGLcore.so.$NV_VERSION libGLcore.so.1
  cd "$CWD"
fi
}

lib_nvidia(){
# removed libglx.so as this is not installed with compat32
for i in libGL.so; do
  if [ "$i" = "libGL.so" ]; then
    cd "$LIB"
  fi
  #If libGL.so.$NV_VERSION-nvidia does exists, then remove the -nvidia and make it usable that way
  if [ -e "$i.$NV_VERSION-nvidia" ]; then
    setup_link "" "$i.$NV_VERSION" "$i.$NV_VERSION-nvidia"
  fi
  cd "$CWD"
done
}

# libglx_base function not needed for compat32
# libglx_nvidia function not needed for compat32
# libglx_xorg function not needed for compat32
# libwfb_nvidia function not needed for compat32

nvidia_ldconfig(){
# NOTE:  This may require running it with /etc/profile.d/32dev.sh
/sbin/ldconfig
#Generate correct symink for that lib
/sbin/ldconfig -l $1

if [ "$2" = "xorg" ]; then
  #Remove so-link, recreated by ldconfig
  cd $LIB
  remove_link "libGLcore.so.1"
  cd $CWD
fi
}

check(){
  echo -n "checking $2...."
  if [ -e "$1/$2" ]; then
    if [ "$3" = "exist" ]; then
      echo "ERROR: $1/$2 does exist!!!!!"
    else
      echo -n "exists"
      if [ -h "$1/$2" ]; then
        echo "(link)"
        echo -n " points to:"
        ls -o "$1/$2" | cut -d ">" -f 2
      else
        if [ "$3" = "link" ]; then
          echo " (!)"
        else
          echo ""
        fi
      fi
    fi
  else
    if [ "$3" = "exist" ]; then
      echo "does not exist"
    else
      echo "ERROR: $1/$2 does not exist!!!!!"
    fi
  fi
}

# check_includes function not needed for compat32

check_glcore(){
  if [ "$1" = "nvidia" ]; then
    CHECK="link"
  else
    CHECK="exist"
  fi

  for i in libGLcore.so.1 libGLcore.so.$NV_VERSION libGLcore.so.$NV_VERSION-nvidia; do
    if [ "$i" = "libGLcore.so.1" ]; then
      check $LIB $i $CHECK
    elif [ "$i" = "libGLcore.so.$NV_VERSION" ]; then
      check $LIB $i $CHECK
    else
      check $LIB $i
    fi
  done

  echo ""
}


# check_glx function not needed for compat32
# check_wfb function not needed for compat32

check_gl(){
  if [ "$1" = "nvidia" ]; then
    nvidia="link"
    EXT=""
  else
    nvidia="exist"
    EXT="-xorg"
  fi

  for i in libGL.la libGL.so libGL.so.1 libGL.so.$NV_VERSION libGL.so.$NV_VERSION-nvidia \
    libGL.so.$GL_VERSION libGL.so.$GL_VERSION-xorg; do
    if [ "$i" = "libGL.so" ]; then
      check $LIB $i "link"
    elif [ "$i" = "libGL.so.1" ]; then
      check $LIB $i "link"
    elif [ "$i" = "libGL.so.$NV_VERSION" ]; then
      check $LIB $i $nvidia
    elif [ "$i" = "libGL.so.${GL_VERSION}${EXT}" ]; then
      check $LIB $i "exist"
    else
      check $LIB $i
    fi
  done

  echo ""
}

nvidia_check(){
  check_gl "nvidia"

  check_glcore "nvidia"
}

xorg_check(){
  check_gl

  check_glcore
}

cleanup_check(){
  check_gl

  check_glcore
}

nvidia(){
  echo $'Switching to nvidia-driver-compat32 files!\n'
  echo "This is ONLY for compat32 nvidia files."
  echo "If you want the 64 bit files, then you have to"
  echo "use the normal nvidia-switch."

  lib_nvidia
  libgl_nvidia
  libglcore_nvidia

  LD_NVIDIA="${LIB}/libGL.so.$NV_VERSION-nvidia"
  nvidia_ldconfig $LD_NVIDIA
}

xorg(){
  echo $'Switching to stock xorg files.\n'
  if [ "$1" = "cleanup" ]; then
    echo $'Cleaning up symlinks.\n'
  fi
  echo "This is ONLY for compat32 xorg files."
  echo "If you want the 64 bit files, then you have to"
  echo "use the normal nvidia-switch."

   libs_basic
   libgl_xorg

   LD_NVIDIA="${LIB}/libGL.so.1.2"
   nvidia_ldconfig $LD_NVIDIA "xorg"
}

usage(){
  echo "NOTE! nvidia-switch32 only manages the 32bit multilib files. you must use the"
  echo "normal nvidia-switch for the 32bit driver files.\n"
  echo "Usage:"
  echo " --nvidia		Switch to 32bit compat nvidia driver files"
  echo " --xorg			Switch to 32bit xorg files"
  echo " --cleanup		Switch to 32bit xorg files and remove all created symlinks"
  echo " --install		Switch to 32bit nvidia driver files"
  echo "			  This is used on installation to handle installroot correctly"
  echo "			  Please use --nvidia for after-install switches instead"
  echo " --check-nvidia		Check if everything is setup correctly for nvidia's 32bit driver"
  echo " --check-xorg		Check if everything is setup correctly for xorg's 32bit driver"
  echo " --check-cleanup	Check if everything has been cleaned up correctly"
  echo " --help			Show this help message"
}

# There are some people out there that may have installed this by accident
# on a slackware 32bit os.  Lets help them out a bit.
if [ $(uname -m) != "x86_64" ]; then
    echo "ERROR: nvidia-switch32 is for managing the 32bit multilib files that would"
    echo "be installed on a 64bit system after a normal slackware64 install."
    echo "'uname -m'  Tells me you are currently not running an x86_64 kernel.\n"
    usage
    exit 1
fi

if [ "$1" = '--nvidia' ]; then
  nvidia
elif [ "$1" = '--install' ]; then
  ROOT=""
  CWD=$(pwd)
  # Force LIBSUFFIX for compat32
  LIBSUFFIX=""
  LIB="${ROOT}usr/lib${LIBSUFFIX}"
  nvidia
elif [ "$1" = '--xorg' ]; then
  xorg ""
elif [ "$1" = '--check-nvidia' ]; then
  nvidia_check
elif [ "$1" = '--check-xorg' ]; then
  xorg_check
elif [ "$1" = '--check-cleanup' ]; then
  cleanup_check
elif [ "$1" = '--cleanup' ]; then
  xorg "cleanup"
elif [ "$1" = '--help' ]; then
  usage
else
  usage
fi
